config/routes.rb
CarrierWave::Application.routes.draw do

  resources :videos, only: [:index, :new, :create, :destroy]
  root "videos#index"
  
  post "zencoder" => "zencoder#create", :as => "zencoder" # used to direct the "completed job" notification from zencoder
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :attachment, VideoUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
  
	# Note: The "public" directory (i.e. (name of application)/public) can build up with "failed" uploads.  
	# To upload a file, Carrierwave saves a copy of the file to the public folder before it performs 
	# validation.  If validations pass, Carrierwave will remove the temporary directory/files.  On the other 
	# hand, if validations fail, then the temporary directory/files will not get removed.  Subsequently, this
	# can build up quickly when there are lots of failed uploads.
	# For more in about this topic, see http://stackoverflow.com/questions/16138617/rake-aborted-operation-not-permitted-carrierwave-delete-tmp-files-that-failed
	# Possible solutions:
	# 	1.  Used this solution (i.e. remove_tmp_directory() method) - https://github.com/carrierwaveuploader/carrierwave/issues/240
	#  	2.  https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Delete-cache-garbage-directories
	#   3.  use background server to run a rake task to clean this directory periodically - http://stackoverflow.com/questions/19126504/cleanup-tmp-directory-with-carrierwave	
  # after_save is an additional callback that is available after mounting an uploader.  See - https://github.com/carrierwaveuploader/carrierwave
  after_save :remove_tmp_directory  # Removes public/tmp directory which contains "failed" carrierwave uploads.
  
  # The "meta-info" column in the video table can be used to store meta-data attributes by using the store method
  # This functionality is used in app/video_uploader.rb
  # http://api.rubyonrails.org/classes/ActiveRecord/Store.html
  # http://blog.chrisblunt.com/rails-3-storing-model-metadata-attributes-with-activerecordstore/
  store :meta_info, accessors: [ :request, :response ], coder: JSON 
  
  # To locally test the videos, after Zencoder has done
  # transcoding, do following in rails console
  #
  # >> v = Video.find(id) # id of the video model
  # >> v.meta_info = v.meta_info.merge(:response => { :input => { :duration_in_ms => 3000 }, :job => { :state => 'finished' }})
  # >> v.save!
  def duration
    ((meta_info[:response].try(:[], :input).
      try(:[], :duration_in_ms) || 0) / 1000.0).ceil
  end

  def transcode_complete?
    meta_info[:response].try(:[], :job).
      try(:[], :state) == 'finished'
  end
  
  def remove_tmp_directory
	path_to_be_deleted = "#{Rails.root}/public/uploads/tmp"
	#DEBUG: Rails.logger.debug("PATH: #{path_to_be_deleted}")
    FileUtils.remove_dir(path_to_be_deleted, :force => true)
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
# 	Using jquery upload (vs. Carrierwave) to upload videos.  Thus, .fileupload() (assets/javascript/video.js.coffee)
#	has dataType set to "script" which means it is expecting to receive a javascript from the server which
#	in this case comes from the create action in the Videos controller and uses a javascript template (app/views/videos/create.js.erb)
	@video = Video.create(video_params) #creates a new record
	
  
#	Code below is for using Carrierwave to upload videos.  
# 	No need to use coerce method because not using Uploadify (doesn't work on iPhones)  
#	newparams = coerce(params)
		#DEBUG: redirect_to resumes_path, notice: "newparams: #{newparams}"
	
#	@video = Video.new(video_params)
#	#DEBUG: redirect_to videos_path, notice: "newparams: #{newparams}"
#		
#    if @video.save
#		redirect_to videos_path, notice: "The video #{@video.name} has been uploaded."
#		#DEBUG: redirect_to videos_path, notice: "cool - params: #{params}"
#    else
#		render "new"
#		#DEBUG:	render :text => "debug: " + params.inspect
#		#DEBUG:	redirect_to videos_path, notice: "crap - params: #{params}"
#    end
  end

  def destroy
    @video = Video.find(params[:id])

#	http://stackoverflow.com/questions/10054985/how-to-delete-files-recursively-from-an-s3-bucket
#	To delete the entire S3 folder, the aws request but be in the following form:
#	s3.buckets[ENV['AWS_BUCKET']].objects.with_prefix('uploads/video/attachment/89/').delete_all	
	directory_to_be_deleted = File.dirname(@video.attachment.url) # get the directory of a file (e.g. - https://s3.amazonaws.com/barfly_carrierwave/uploads/video/attachment/89)
	bucket = ENV['AWS_BUCKET'] + '/' # need to remove the slash from the url so concatenate with bucket
	directory_to_be_deleted = directory_to_be_deleted.split(bucket)[1] # splits into an array where we keep the 2nd element (e.g. - uploads/video/attachment/89)
	directory_to_be_deleted = directory_to_be_deleted + '/' # need to append a forward slash at the end (e.g. - uploads/video/attachment/89/
#	logger.debug("directory_to_be_deleted: #{directory_to_be_deleted}")
	s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID'], :secret_access_key => ENV['AWS_KEY_VALUE'])
	s3.buckets[ENV['AWS_BUCKET']].objects.with_prefix(directory_to_be_deleted).delete_all # deletes all contents on S3 folder under the video ID

    @video.destroy # destroy the record in the db
    redirect_to videos_path, notice:  "The video #{@video.name} has been deleted."
  end

  
	private

	def video_params
		params.require(:video).permit(:name, :attachment) 
	end

	#   See the following about the coerce(param) method - http://martinjhawkins.wordpress.com/2013/10/07/uploadify-with-paperclip-on-rails-tutorial/	
	#  	Uploadify doesn't put the params (:name and :attachment) in the correct params hash structure
	#  	In order to pass strong parameters enforcement, :name and :attachment need to be nested hashes within the :resume key:
	#  		{ 
	#			:resume => {
	#				:name = <insert name>, 
	#				:attachment = <insert attachment>
	#			} 
	#		}
	#  	Instead, uploadify produces the following params hash:
	#  		{
	#			"Filename"=>"old_town_pub.mp4", 
	#			"authenticity_token"=>"dT2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BKk=", 
	#			"_CarrierWave_session"=>"dXhXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx03a77bffb", 
	#			"Filedata"=>#<ActionDispatch::Http::UploadedFile:0x2ccf8e0 @tempfile=#<File:C:/Users/MICHAE~1/AppData/Local/Temp/RackMultipart20140904-2140-15cy0hb>, @original_filename="old_town_pub.mp4", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"Filedata\"; filename=\"old_town_pub.mp4\"\r\nContent-Type: application/octet-stream\r\n">, 
	#			"Upload"=>"Submit Query"
	#		}
	# 	No need to use coerce method because not using Uploadify (doesn't work on iPhones)  
#	def coerce(params)
#		if params[:video].nil?
#			params[:video] = Hash.new
#			
#			# set file name
#			if params[:name].nil?
#				params[:video][:name] = DateTime.now.strftime("%b %e, %Y @%l:%M %p")
#			else
#				params[:video][:name] = params[:name]
#				params[:name].delete
#			end 
#			
#			# nest attachment
#			params[:video][:attachment] = params[:attachment]
#	  
#			# use setContentType to determine the MIME format (so not always set to 'application/octet-stream')
#			params[:video][:attachment].content_type = setContentType(params[:attachment].original_filename)
#			# DEBUG: render :text => "debug: " + params[:attachment].original_filename.inspect	  # "american_junkie.mp4"
#			params.delete(:attachment)  # remove the extra :attachment parameter from the params hash
#
#			params[:video]
#		else
#			params
#		end
#	end

#	No need for setContentType because not using Uploadify (doesn't work on iPhone)	
#	def setContentType(originalFileName)
#	
#		fileExtension = originalFileName.split('.').last.downcase # take the last (2nd) element of the newly created array, split by the period - this should be the file extension (i.e. mp4, MOV, etc.)
#		
#		case fileExtension
#			when "mp4"
#				return "video/mp4"
#			when "mov"
#				return "video/quicktime"
#		end
#		
#	end
  
end

app/views/videos/_video.html.erb
<div class="video">
  <%= link_to image_tag(thumb(video.attachment_url)), video if video.attachment? %>
  <div class="name"><%= video.name %></div>
  <div class="actions">
    <%= link_to "remove", video, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/videos/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/videos/create.js.erb
<% if @video.new_record? %>
  alert("Failed to upload video: <%= j @video.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#videos").append("<%= j render(@video) %>");
<% end %>

app/views/videos/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/videos/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>	  


<!-- form below uses jquery file upload (vs. carrierwave) to upload videos -->
<div class="well">
  <!-- Need to set multipart to true if doing a file upload -->
  <!-- form has class="new_video", id="new_video", action="/videos", method="post" -->
  <!-- action: "/videos" + method: "post" = controller: videos + action: create -->
  <%= form_for Video.new, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment, multiple: true, name: "video[attachment]" %>
  <% end %>
</div>

<div id="videos">
  <%= render @videos %>
</div>
<div class="clear"></div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>download link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <td><%= link_to "Watch Video", video.attachment_url %></td>
        <td><%= button_to "Delete", video, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{video.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<!-- Progress bar -->
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%;"></div></div>
</div>
</script>






<% if false %> <!-- code below uses Carrierwave (vs. jquery upload gem) to upload videos -->
<br />
<%= link_to "New Video", new_video_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <td><%= link_to "Watch Video", video.attachment_url %></td>
        <td><%= button_to "Delete", video, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{video.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %> <!-- using Carrierwave -->

</div> <!-- container -->

app/views/videos/new.html.erb
<% if !@video.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="well">
  <!-- Need to set multipart to true if doing a file upload -->
  <%= form_for @video, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>



<% if false %>
UPLOADIFY CODE BELOW: Commenting out because it is flash based and doesn't work on iphone
<div id="file_upload"></div>

<!-- 
Uploadify resources:
1.  Rails 3 - http://martinjhawkins.wordpress.com/2013/10/07/uploadify-with-paperclip-on-rails-tutorial/	
2.  Rails 4 - http://vignesh.info/blog/rails-4-uploadify-paperclip/ 
3.  Rails 3 - http://www.damiangalarza.com/posts/ruby-on-rails/using-uploadify-with-rails-3/
4.  Rails 3 - http://www.nickdesteffen.com/blog/video-encoding-with-uploadify-carrierwave-and-zencoder
5.  Rails 3 - http://erniemiller.org/2010/07/09/uploadify-and-rails-3/
-->


<script type="text/javascript">
  $(function() {
    <% session_key = Rails.application.config.session_options[:key] %>
    var uploadify_script_data = {};
    var csrf_token = $('meta[name=csrf-token]').attr('content');
    var csrf_param = $('meta[name=csrf-param]').attr('content');

/*
	Note: 
	- Code for uploadify_script_data variable is different than that shown in : http://www.nickdesteffen.com/blog/video-encoding-with-uploadify-carrierwave-and-zencoder
	- It was: 
	
		uploadify_script_data[csrf_param] = encodeURI(encodeURIComponent(csrf_token)); 
		
	But encodeURIComponent was causing an Invalid Authorization Token error.  Code below is consistent with the other two sources cited above.	
*/

    uploadify_script_data[csrf_param] = encodeURI(csrf_token);
    uploadify_script_data['<%= session_key %>'] = '<%= cookies[session_key] %>';
	
    $('#file_upload').uploadify({
      'swf'  		: '<%= asset_path("uploadify.swf") %>',
      'uploader'  	: '<%= videos_path %>',
	  'formData' 	: uploadify_script_data,
	  'fileObjName'	: 'attachment',
      'buttonText' 	: 'Upload Video',
	  'method'		: 'post',
	  'removeCompleted' : true,
	  'multi'		: false,
      'auto'      	: true
    });
  });
</script>
<% end %>